### ISSUE TITLE
Add documentation on retrieving iss and kid

### ISSUE THREAD

**Issue by roux1max** [Snapchat/storykit#10]
Hi there !

I was searching the web on how to get the `iss` and `kid` from the Snap advocate but I cannot find anything. Can you provide more information on that?

Thanks

**Comment by roux1max** [comment]
Also @raRaRa I saw you posted 2 issues as well, do you have information on the subject?

**Comment by raRaRa** [comment]
Hi @roux1max  - have you been accepted into the early access? Someone from Snap will send you `iss` and `kid` once you've been accepted. You can apply here: https://kit.snapchat.com/#story-kit

**Comment by roux1max** [comment]
Thanks a lot for the quick answer ! No I didn't, it seemed to me it was already out. I must have missed that. Thanks !
